// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "CausalSurvival_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// computeSubsetInformationMatrix
MatrixXd computeSubsetInformationMatrix(const Map<CsrMatrix> X, const Map<VectorXd> weight, int subsetSize);
RcppExport SEXP _CausalSurvival_computeSubsetInformationMatrix(SEXP XSEXP, SEXP weightSEXP, SEXP subsetSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Map<CsrMatrix> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Map<VectorXd> >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< int >::type subsetSize(subsetSizeSEXP);
    rcpp_result_gen = Rcpp::wrap(computeSubsetInformationMatrix(X, weight, subsetSize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CausalSurvival_computeSubsetInformationMatrix", (DL_FUNC) &_CausalSurvival_computeSubsetInformationMatrix, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_CausalSurvival(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
