# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeSubsetSparseInformationMatrix <- function(X, weight, subsetSize) {
    .Call(`_CausalSurvival_computeSubsetSparseInformationMatrix`, X, weight, subsetSize)
}

computeSubsetInformationMatrix <- function(Y, weight, subsetSize) {
    .Call(`_CausalSurvival_computeSubsetInformationMatrix`, Y, weight, subsetSize)
}

computeSubsetMatrix <- function(X, weight, Y, subsetSize) {
    .Call(`_CausalSurvival_computeSubsetMatrix`, X, weight, Y, subsetSize)
}

computeSubsetSparseMatVec <- function(X, v, subsetSize, transposed = TRUE) {
    .Call(`_CausalSurvival_computeSubsetSparseMatVec`, X, v, subsetSize, transposed)
}

computeSubsetMatVec <- function(Y, v, subsetSize, transposed = TRUE) {
    .Call(`_CausalSurvival_computeSubsetMatVec`, Y, v, subsetSize, transposed)
}

