---
title: "Vignette"
author: "Shiyao Xu"
date: "1/19/2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
devtools::load_all("/Users/shiyaoxu/Documents/Research/CausalSurvival")
```

## Load data

Use synthetic `Eunomia` dataset to illustrate how to perform the simulation study. 

```{r}

connectionDetails <- Eunomia::getEunomiaConnectionDetails()
Eunomia::createCohorts(connectionDetails)

cohortMethodData <- CohortMethod::getDbCohortMethodData(connectionDetails = connectionDetails,
                                                        cdmDatabaseSchema = "main",
                                                        targetId = 1,
                                                        comparatorId = 2,
                                                        outcomeIds = 3,
                                                        exposureDatabaseSchema = "main",
                                                        outcomeDatabaseSchema = "main",
                                                        exposureTable = "cohort",
                                                        outcomeTable = "cohort",
                                                        covariateSettings = FeatureExtraction::createDefaultCovariateSettings())

population <- CohortMethod::createStudyPopulation(cohortMethodData = cohortMethodData,
                                                  outcomeId = 3,
                                                  riskWindowEnd = 99999)

covariateData <- filterAndTidyCovariatesForPs(cohortMethodData, population)
covariates <- covariateData$covariates
row_id <- covariates %>% dplyr::pull(.data$rowId)
covariate_id <- covariates %>% dplyr::pull(.data$covariateId)
val <- covariates %>% dplyr::pull(.data$covariateValue)
covariates <- data.frame(rowId=row_id, covariateId=covariate_id, covariateValue=val)

treatment <- population$treatment
event_time <- population$survivalTime
id <- 1:length(treatment)
rm(list=c("row_id", "covariate_id", "val", "covariateData", "cohortMethodData", "connectionDetails", "population"))
```

Simulate censoring time seperately for each treatment group. 

```{r}
censoring_time
```


## Initial parameters
### PS calculation from real data

```{r}
treatProb <- estimateTreatProb(id=id, treatment=treatment, covariates=covariates, covIdTreatProb=NULL)
```

### Survival and censoring hazards from real data

```{r}
estimatedSurvHazard
```


## Simulation 


















